import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import './globals.css'

import { Toaster } from '@/components/ui/sonner'

import { ThemeProvider } from '@/components/theme-provider'
import { Header } from '@/components/header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <div className='mx-auto w-full max-w-7xl items-center'>
            <Header />
          </div>

          {children}
          <Toaster
            // toastOptions={{
            //   unstyled: true,
            //   classNames: {
            //     error: 'bg-red-400 p-2 rounded-md text-white p-2 ',
            //     success:
            //       'border-gray-500 border-2 text-green-800 p-2 rounded-md ',
            //     warning:
            //       'border-gray-500 border-2 text-orange-500 p-2 rounded-md ',
            //     info: 'border-gray-500 border-2 text-blue-500 p-2 rounded-md '
            //   }
            // }}
            position='top-center'
            richColors
          />
        </ThemeProvider>
      </body>
    </html>
  )
}
